package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/NON_EXISTENT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u152/9280.nc/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Tuesday, June 20, 2017 4:13:57 PM PDT
*/

public interface NON_EXISTENT
{

  /** Object adapter state indicating that the adapter has been destroyed.
   */
  public static final short value = (short)(4);
}
